### ISSUE TITLE
ValueError: C is not a recognized temperature unit

### ISSUE THREAD

**Issue by smiths78** [ironsheep/lovelace-rpi-monitor-card#22]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
core-2022.3.2
**Last working release (if known):**
not sure - probably 2022.2.x
**Browser and Operating System:**

Safari on MacOS
**Description of problem:**

I get a very frequent message saying 'ValueError: C is no a recognised temperature unit' although the Lovelace display looks correct, giving the temperature in C, so the problem may be just cosmetic, but odd.
Occurs for all of my RPIs except for the one running Home Assistant.
Home Assistant runs on Bullseye on RPi4. Others run on Bullseye and Buster including RPi 3b, RPi 0, RPi 4.

Typical Lovelace card setup:

type: conditional
conditions:
  - entity: sensor.rpi_monitor_applepi
    state_not: unavailable
card:
  type: custom:rpi-monitor-card
  card_style: glance
  entity: sensor.rpi_monitor_applepi
  fs_severity:
    - color: Green
      from: 0
      to: 25
    - color: Orange
      from: 26
      to: 50
    - color: Red
      from: 51
      to: 100

The following is in the logs:

Logger: homeassistant.helpers.event
Source: util/temperature.py:44 
First occurred: 16:56:56 (22 occurrences) 
Last logged: 17:10:20

Error while processing state change for sensor.rpi_temp_blackcurrantpi
Error while processing state change for sensor.rpi_temp_applepi
Error while processing state change for sensor.rpi_temp_damsonpi
Error while processing state change for sensor.rpi_temp_bananapi
Error while processing state change for sensor.rpi_temp_rhubarbpi
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/event.py", line 273, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 530, in async_run_hass_job
    cast(Callable[..., _R], hassjob.target)(*args)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/homekit/accessories.py", line 413, in async_update_event_state_callback
    self.async_update_state_callback(event.data.get("new_state"))
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/homekit/accessories.py", line 435, in async_update_state_callback
    self.async_update_state(new_state)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/homekit/type_sensors.py", line 120, in async_update_state
    temperature = temperature_to_homekit(temperature, unit)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/homekit/util.py", line 389, in temperature_to_homekit
    return round(temp_util.convert(temperature, unit, TEMP_CELSIUS), 1)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/util/temperature.py", line 44, in convert
    raise ValueError(UNIT_NOT_RECOGNIZED_TEMPLATE.format(from_unit, TEMPERATURE))
ValueError: C is not a recognized temperature unit.
**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by smiths78** [comment]
Sorry, wrong component, it's clearly not the custom card
